trigger:
- main  # Runs pipeline when changes are pushed to the main branch

pool:
  name: SplitStats Machine  # Uses the existing agent on your Windows Server

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.20.4'  # Ensures correct Node.js version

- script: |
    cd "$(Build.SourcesDirectory)\repomoddingwiki"
    echo "Current Directory:"
    pwd
    echo "Installing dependencies..."
    npm install
    echo "Building VitePress site..."
    npm run build
  displayName: 'Build VitePress site'

- script: |
    echo "Checking if build output exists..."
    if exist "$(Build.SourcesDirectory)\repomoddingwiki\docs\.vitepress\dist\index.html" (
        echo "Build successful, proceeding with deployment..."
        robocopy "$(Build.SourcesDirectory)\repomoddingwiki\docs\.vitepress\dist" "C:\IISSites\repomodswiki" /MIR
    ) else (
        echo "Build failed! No dist/index.html found."
        exit /b 1
    )
  displayName: 'Deploy to IIS'

- script: |
    iisreset
  displayName: 'Restart IIS'